### ISSUE TITLE
After opening the MOD of '81 Tiles 2 TESTING', the water pipes cannot be directly connected between the two public buildings in the water supply tab. 

### ISSUE THREAD

**Issue by KearneyXu** [algernon-A/EightyOne2#3]
<img width="1335" alt="屏幕截图(24)" src="https://user-images.githubusercontent.com/113991566/191259569-3d8daa70-a866-4b67-ab14-588fbf7c327e.png">
<img width="1227" alt="屏幕截图(25)" src="https://user-images.githubusercontent.com/113991566/191260530-a5f93463-ee69-4752-bff1-c0a287aa3d16.png">
<img width="1237" alt="屏幕截图(26)" src="https://user-images.githubusercontent.com/113991566/191260630-af8a4539-45d7-4081-99c2-403da3872c4e.png">

A public building is required to lay the water pipes to a part of the underground and then connect to another public building.

**Comment by algernon-A** [comment]
I'm unable to reproduce this issue.  Does it happen with all other mods disabled?

**Comment by KearneyXu** [comment]
After turning off '81 Tiles 2 TESTING', everything is normal. I turned on the 81 grid option directly, and then placed two public buildings near the edge of the map, so the water pipes could not be directly connected.

**Comment by algernon-A** [comment]
Yes, but did you have any other mods active at the time?  If so, can you reproduce with all other mods disabled?

**Comment by KearneyXu** [comment]
Then I will try disabling all modules now and see if there is still an error, sorry for that

**Comment by KearneyXu** [comment]
After disabling all MODs, everything is normal, it is estimated that there is a MOD conflict, but no error is reported, thank you very much

**Comment by algernon-A** [comment]
Please let me know if you can find the mod responsible.

**Comment by KearneyXu** [comment]
Ok, I will try MOD one by one. If I find out, I will tell you in the post. It hurts because there are too many MODs.

**Comment by KearneyXu** [comment]
**Found a conflict between '81 Tiles 2 TESTING' and 'Network Anarchy Beta'.**

When I create a new map, the in-game language of '81 Tiles 2 TESTING' selects 'Simplified Chinese', and when the option 'Unlock all areas' is turned on, the above problem is likely to occur.

When I create a new map, select 'English' in the in-game language of '81 Tiles 2 TESTING', and turn on the option of 'Unlock all areas' with a small probability that the above problem will occur.
![屏幕截图(30)](https://user-images.githubusercontent.com/113991566/191282632-34bd93e1-345a-4fcb-95f3-1aaf8d6f3456.png)
my test map
![屏幕截图(28)](https://user-images.githubusercontent.com/113991566/191282947-4a3a3323-db9e-4dd0-9cfc-14fa6b948e1c.png)
mods i loaded
![屏幕截图(31)](https://user-images.githubusercontent.com/113991566/191286123-474cd470-dec4-437b-b9d7-31d453edc051.png)

**Comment by Leo512bit** [comment]
I do have to wonder if this is a bug with Network Anarchy rather then an incompatibly because I tried loading the game with just Network Anarchy and I am having the same issue. (For the record I'm also having the issue in my main city that as both and it also effects the ferry path tool. I did find that using anarchy lets you bypass this bug.)

**Comment by algernon-A** [comment]
It's very strange - hopefully Quboid might have some insight.

**Comment by Quboid** [comment]
I have identified the problem, it is because Network Anarchy 3 is attempting to apply straight-slope to pipes, which isn't possible.

**Comment by algernon-A** [comment]
Mystery solved!
